### ISSUE TITLE
backlight dont turn off on spectrum screen

### ISSUE THREAD

**Issue by Hunterfnet** [egzumer/uv-k5-firmware-custom#310] opened 2023-12-21 12:43 UTC
as said on title , another fantastic issue

**Comment by gartnl** [comment] 2023-12-21 12:54
This is by design. You can turn it of with sidebutton i assigned to backlight.
I don't regard it an issue as I want to see where signals are and impact on battery is neglictable.

**Comment by Hunterfnet** [comment] 2023-12-21 13:02
i assumed too your response , then the design is bad when i set a backlight default time it's a generic design too , dont need that or make mistakes as generic designs. That's the easiest way

**Comment by gartnl** [comment] 2023-12-21 13:25
Well, compile your own firmware than .... The design is not bad. The whole idea behind a bandscope or spectrum analyser is to look at it so you would expect the backlight to be on.  And you still have the option to turn it off. 

Perhaps it is your understanding of English but a remark like 'another fantastic issue' does not sound nice to egzumer. It sounds like you blame him. But don't forget he is putting a lot of time and effort into this and all for free!

**Comment by Hunterfnet** [comment] 2023-12-21 13:35
i'm here reporting issues , as you can see , not for try sell a mistake like a fantastic evolution and not for compiling nothing . If i compiles something i try make the best before i place like a big software version. And certainly is another  issue as you can see a lot here, nothing more.
On other face , all engineers know about what i'm speaking , you seems that not. Maybe i'm a bad day too today , like all people on any day ;) . Nice day and good work

**Comment by mentanah** [comment] 2023-12-21 13:52
Thank you egzumer, for your excellent work and frequently releasing new updates. 
You are doing a great job for a lot of people here for sure!

**Comment by Hunterfnet** [comment] 2023-12-21 14:05
on my country this is called "palmeros" 
I don't placed wood on fire guys , for same rule dont need a timeout for backlight . When one is on stand by on a frequency , same on the spectrum , when the signal is hard enough the light turns on and heard something. Pls. don't try make the people little for make feel yours better , that dont works . Cya

**Comment by egzumer** [comment] 2023-12-21 14:17
This is how it was designed by fagci, I don't see a reason for changing that

**Closed by egzumer** 2023-12-21 14:17 UTC
