### ISSUE TITLE
S-meter values too high in AM

### ISSUE THREAD

**Issue by iz4hca** [egzumer/uv-k5-firmware-custom#92] opened 2023-11-08 13:54 UTC
only smeter to much open in AM (agc?), then would be perfect!
is the best firmware until right now!👍

**Comment by rai4424** [comment] 2023-11-08 14:28
I m very surprised that FW is improving day by day، with limited memory its a big acheavment to add awsome funtions

**Comment by iz4hca** [comment] 2023-11-08 15:06
> I m very surprised that FW is improving day by day، with limited memory its a big acheavment to add awsome funtions

absolutely!!👍

**Comment by egzumer** [comment] 2023-11-08 15:24
Thank you.
This is basically a duplicate of #53. Please go there, you will find a firmware there that displays raw RSSI value. If you have any way of telling what is the correlation between RSSI and correct value of dBm across spectrum (ideally 3 points per band) I could try to calibrate it. I'm not a ham operator and my knowledge is limited in this regard, also I don't know what kind of accuracy is satisfactory.
The dBm currently is calculated as `(rssi / 2) - 160` which comes from RF IC reference manual, but it looks like to me that it is shifted, and shows to high values.

**Comment by iz4hca** [comment] 2023-11-08 20:41
> Thank you. This is basically a duplicate of #53. Please go there, you will find a firmware there that displays raw RSSI value. If you have any way of telling what is the correlation between RSSI and correct value of dBm across spectrum (ideally 3 points per band) I could try to calibrate it. I'm not a ham operator and my knowledge is limited in this regard, also I don't know what kind of accuracy is satisfactory. The dBm currently is calculated as `(rssi / 2) - 160` which comes from RF IC reference manual, but it looks like to me that it is shifted, and shows to high value

  is enough to reduce a bit, not important be very precis.... try and we check...😉

**Comment by egzumer** [comment] 2023-11-08 21:09
Reduction in dBm
-30, // band 1
-36, // band 2
-54, // band 3
-48, // band 4
-48, // band 5
-48, // band 6
-12  // band 7

[reduced_rssi.packed.bin.zip](https://github.com/egzumer/uv-k5-firmware-custom/files/13301320/reduced_rssi.packed.bin.zip)

**Comment by iz4hca** [comment] 2023-11-08 21:55
> Reduction in dBm -30, // band 1 -36, // band 2 -54, // band 3 -48, // band 4 -48, // band 5 -48, // band 6 -12 // band 7
> 
> [reduced_rssi.packed.bin.zip]

so is too much, the pic show the difference,  in the middle of the last 2 release would be good👍

https://drive.google.com/file/d/1GmxOpAJev4ZpZjo76cbZLNbAKTJ6UXRL/view?usp=drivesdk

TNX MATE !

**Comment by iz4hca** [comment] 2023-11-10 13:43
Egzumer, the first reduce release is much hard, try this when you have a bit of time please🙏:
b1: -15 
b2: -15
b3: -25
b4: -20
b5: -20
b6: -20
b7: -7

**Comment by iz4hca** [comment] 2023-11-20 21:14
.. that's the right value! much more real, good job! 👍🙏

**Comment by iz4hca** [comment] 2023-11-20 21:16
...also the AM audio quality seem more clear, less noise 👌

**Comment by egzumer** [comment] 2023-11-20 21:19
> ...also the AM audio quality seem more clear, less noise 👌

Placebo effect, there is no change regarding that. Also the s-meter values are as you suggested, so good job for both of us.
Feedback from other users is also welcome.

**Comment by iz4hca** [comment] 2023-11-20 21:26
i said "SEEM" but only few minuts of testing, maybe placebo.... or maybe propagation🤷, anyway  the signal strength now is ok 👏👏

**Closed** 2023-11-22 13:52 UTC
Labels: duplicate
