### ISSUE TITLE
Frequency scan monitor (F5) overloads AM reception

### ISSUE THREAD

**Issue by Superkatzo** [egzumer/uv-k5-firmware-custom#240] opened 2023-12-12 00:32 UTC
Version # is **0.19**

If i search the Airband with normal scanmode (longpress scan) i find the Airport and it sounds ok...same as when i put the frequency directly in.

But when i go to the frequency scan/monitor with **F  5** and bump trough it (in 8.33 / AM )with the **up** and **down** buttons 
the AM sound brakes down.Sounds like the speaker overloads, even when directly on the airport frequency with pressing 5 in this mode.
If switched to usb it sounds a bit better but still not normal.

When going back to the normal frequency mode modulation is good again.

Btw while bumbling around there in scanner/monitor mode ,flipping fast between ranges and am/fm/usb there where 2 times where the handset froze and i had to restart...

So... it seems the frontend overloads but only in the frequency scan/monitor mode ?! dunno, just thought i would report this and say

thank you for you work mate...well done :)

**Comment by egzumer** [comment] 2023-12-12 01:21
duplicate of #113

**Closed by egzumer** 2023-12-12 01:21 UTC
Labels: duplicate
