### ISSUE TITLE
Backlight brightness <10 creates 996Hz tone in transmission

### ISSUE THREAD

**Issue by LordVertice** [egzumer/uv-k5-firmware-custom#405] opened 2024-01-11 08:30 UTC
If the backlight is on, but specifically not at brightness 10, there's a continuous 996Hz tone when transmitting (not audible on own end).

It's louder the brighter you set the backlight, I can personally start hearing it on 6. It's quite loud on 9, but disappears entirely on 10.

Is this a hardware issue, or can this be fixed in software?

**Comment by JuantAldea** [comment] 2024-01-11 08:38
Brightness is controlled by PWM, that is for sure producing RF noise.

**Comment by tomaswcz** [comment] 2024-01-11 09:31
Could by fixed by either turning the backlight off/full during transmission or maybe changing the PWM frequency.

**Comment by egzumer** [comment] 2024-01-12 15:27
Backlight PWM runs on 1kHz, and yes it is audible in some situations, but it rarely happens on my radio, and it usually used to disappear when I changed it's position. I even tried to reproduce this issue right now and I'm unable to.
Most firmwares don't implement this feature precisely because of that issue. Here you are able to set it to max or off and it should be gone.
You can also try setting BltTRX to RX or OFF.
Or play with frequency setting:
https://github.com/egzumer/uv-k5-firmware-custom/blob/9472bbb58badaebee6f0f758c775530047667b14/driver/backlight.c#L31
There is just one caveat, if frequency is set too high setting of 1 stops working and behaves as 0.

**Comment by JuantAldea** [comment] 2024-01-12 15:34
> I'm not familiar with how PWM works, so I believe your assessment as a collaborator. But from what I can tell (from my admittedly short google search) I'd expect a PWM signal to be an interval rather than a continuous tone (or an interval fast enough to sound like a tone, changing in frequency depending on the setting), and/or sounding like a square wave.

See https://www.youtube.com/watch?v=wT9R1aUUttw

**Comment by gartnl** [comment] 2024-01-13 10:13
@LordVertice In answer to your first question: it is hardware. The device has no shielding between different blocks of functionality.
Normally you would see tiny tin cans over the different blocks, and any copper traces with AC routed in such a way that they don't interfere. The UV-x has none of this. I suspect the PWM is picked up by the microphone amp.

**Closed** 2024-01-20 19:26 UTC

**Comment by acbits** [comment] 2024-04-30 22:36
I have compiled with PWM set to 4000 Hz. It boots and works normally. 

Check whether it solves your problem.
