### ISSUE TITLE
Main Only RX, make the display more simple. (only show one VFO)

### ISSUE THREAD

**Issue by SutliffeProductions** [egzumer/uv-k5-firmware-custom#536] opened 2024-04-01 19:30 UTC
Hi Guys, this firmware is great. My only problem is complexity for family use, plus my eyes are not that good. Personally, I run my radio solely in main only RX mode i don't really ever use the second VFO. therefore i would like if i could have only one VFO displayed at a time in this mode (Or another mode, i don't mind) still being able to switch between a and b could be nice, however if the main thing is that if only 1 VFO is displayed, the main font could be larger, and easier on my eyes.  

Thanks guys,
let me know if I'm completely wrong and this is not a valid request.

**Comment by jonnycastaway** [comment] 2024-04-02 06:48
I also want such feature.

**Comment by akira25** [comment] 2024-04-02 21:48
related to (or duplicate of) #124

**Closed as not planned** 2024-04-02 22:16 UTC
Labels: duplicate
